version: '3'
services:

  mariadb:
    image: mariadb:latest
    restart: always
    network_mode: host
    environment:
      MARIADB_ROOT_PASSWORD: root

    volumes:
      - ./services/mariadb/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - type: bind
        source: ./services/mariadb/mysql/conf.d/server.cnf
        target: /etc/mysql/conf.d/server.cnf
      - type: bind
        source: ./services/mariadb/mysql/encryption
        target: /etc/mysql/conf.d/encryption
      - type: bind
        source: ./services/rootCA/rootCA.crt
        target: /etc/mysql/conf.d/encryption/tls/rootCA.crt
          #vault:
          # image: hashicorp/vault:latest
          #container_name: vault
          #ports:
          #  - "8200:8200"
          #volumes:
          #  - /services/vault/vault.hcl:/vault/config/vault.hcl
          #  - /services/vault/data:/vault/data
          #cap_add:
          #  - IPC_LOCK
          #environment:
          #  VAULT_ADDR: http://127.0.0.1:8200
          #restart: unless-stopped

volumes:
  configuration:
    name: configuration

