version: '3'
services:

  mariadb:
    image: mariadb:latest
    restart: always
    network_mode: host
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./services/mariadb/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - type: bind
        source: ./services/mariadb/my.cnf.d/server.cnf
        target: /etc/mysql/conf.d/server.cnf
          # adminer:
          #image: adminer:latest
          #restart: always
          #network_mode: host
          #ports:
          #- 8090:8080

volumes:
  configuration:
    name: configuration
